### ISSUE TITLE
Link in main docs to @Endpoint API is incorrect

### ISSUE THREAD

**Issue by JoshuaCWebDeveloper** [micronaut-projects/micronaut-docs#13]
In the main docs at https://docs.micronaut.io/latest/guide/index.html#endpointAnnotation, the link for `@Endpoint` points to the old location at https://docs.micronaut.io/latest/api/io/micronaut/management/endpoint/Endpoint.html, it should instead point to the correct location at https://docs.micronaut.io/latest/api/io/micronaut/management/endpoint/annotation/Endpoint.html.

**Comment by graemerocher** [comment]
Thanks, have you considered submitting a PR? Just click "Improve this Doc" in the top right next to each section title
