### ISSUE TITLE
Remove the version dropdown via CSS

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-docs#148]
I think we should remove the dropdown in the HTML since it is causing more confusion than benefit.

![CleanShot 2024-01-26 at 17 21 37@2x](https://github.com/micronaut-projects/micronaut-docs/assets/864788/ce145bf1-d9d1-4dd9-ac1c-a8a003c48407)

I suggest we remove it via CSS. 

@micronaut-projects/core-developers thoughts?

**Comment by wetted** [comment]
This will always point to LATEST? What if someone is stuck on Micronaut 3 and needs docs for that? They just need to know to change the docs URL?

**Comment by burtbeckwith** [comment]
What confusion?

**Comment by andriy-dmytruk** [comment]
Perhaps latest/snapshot should also include the actual version, e.g. `4.0.0 (Latest)`?

**Comment by alvarosanchez** [comment]
I find it useful. What is the confusion that it causes?

**Comment by sdelamo** [comment]
Since Micronaut Framework 4, the framework version is not the core version. The people see 4.3.2 in the main docs (the core documentation) and they expect a version of the framework of 4.3.2. and that may not exists. In general, people should always go to `latest` unless they want to go a previous major version of the docs which they can change via the URL.

**Comment by melix** [comment]
I'm fine with removing the dropdown. If we decide to go this route it requires changes in `micronaut-build` which has tasks to deal with it.

**Comment by alvarosanchez** [comment]
Oh, you meant the core version...

I would agree to remove it only from core docs. But for the modules I still find it useful

**Comment by sdelamo** [comment]
> Oh, you meant the core version...
> 
> I would agree to remove it only from core docs. But for the modules I still find it useful

I mean for every module. But core cause the most confusion. I

**Comment by sdelamo** [comment]
> I'm fine with removing the dropdown. If we decide to go this route it requires changes in `micronaut-build` which has tasks to deal with it.

I assume we need a release of docs with the css changes.

**Comment by melix** [comment]
Not necessarily, we can change the release dropdown task, which is simply post-processing the HTML, to remove that section, possibly as an option.

**Comment by osscontributor** [comment]
If the drop down is removed, can we provide a page or nav bar or something that lists versions of Micronaut Platform that have been released and links to the docs for the version of the User Guide that corresponds to the version of core that that version of Micronaut Platform depends on by default?

**Comment by osscontributor** [comment]
> The people see 4.3.2 in the main docs (the core documentation) and they expect a version of the framework of 4.3.2. and that may not exists.

I agree that causes confusion.

Personally, I like the drop down but I wish that the version numbers scheme was such that the version of Micronaut Platform that I am using is the version I should select in that list.  Folks often don’t necessarily know what version of core they are using because they don’t necessarily ever specify that version number or see it anywhere.  They do know the version of platform they are using.  

If I install micronaut using SdkMan and I install it with “sdk install micronaut 3.8.9” 3.8.9 is the version of Platform I am installing, not necessarily the version of core I will be using, and when I want to use it I do that with “sdk use micronaut 3.8.9”.  When I go to reference the User Guide for that I would expect to go to version 3.8.9 of the User Guide.  For some of our releases the platform version and the core version happen to the be the same and for some they don’t.

I like the idea of being able to easily find docs for the version of Micronaut that I installed.

**Comment by osscontributor** [comment]
> If the drop down is removed, can we provide a page or nav bar or something that lists versions of Micronaut Platform that have been released and links to the docs for the version of the User Guide that corresponds to the version of core that that version of Micronaut Platform depends on by default?

Just re-raising that question.  Thank you for your feedback!

**Comment by sdelamo** [comment]
We could generate a version of https://docs.micronaut.io/index.html with links to the docs versions of particular platform release. 

and generate a index431.html and index430.html etc per release. `index.html` would be always the latest stable release. 

So the link of the user guide for core will point to 

![CleanShot 2024-02-13 at 09 22 17@2x](https://github.com/micronaut-projects/micronaut-docs/assets/864788/730d03c6-35ea-4a7b-aa72-532c73ce1c6a)

Instead of https://docs.micronaut.io/latest/guide the link will be https://docs.micronaut.io/4.3.5/guide/

Instead of https://micronaut-projects.github.io/micronaut-data/latest/guide/ the link will be https://micronaut-projects.github.io/micronaut-data/4.6.1/guide/index.html

**Comment by osscontributor** [comment]
If I understand that correctly, I think that sounds good. What I think would be helpful is if I know the version of platform that I am using (I think that is the version number that most folks think about when they think about) then I would like to be able to navigate to the docs for the version of core that is configured by default in a newly created Micronaut app for that version of platform.

**Comment by osscontributor** [comment]
Would there be a navbar or page that lists released versions of platform and provide links to the docs for the version of core that is configured by default for that version of platform?

**Comment by osscontributor** [comment]
> We can also, try to add a dropdown to in docs.micronaut.io to go change the version.

Thank you!

**Comment by timyates** [comment]
I believe this is done 👍
