### ISSUE TITLE
Improve this doc links don't work

### ISSUE THREAD

**Issue by ZacharyKlein** [micronaut-projects/micronaut-docs#23]
Tested on the following sites:

- https://docs.micronaut.io/latest/guide/index.html
- https://micronaut-projects.github.io/micronaut-data/snapshot/guide/index.html
- https://micronaut-projects.github.io/micronaut-cache/snapshot/guide/

Issue seems to be a line break in the Github URL after the branch name: 

```
<button type="button" class="btn btn-default" onclick="window.location.href=&quot;https://github.com/micronaut-projects/micronaut-data/edit/master
/src/main/docs/guide/sql/jdbc/sqlMapping/sqlCompositeId.adoc&quot;">
        <i class="fa fa-pencil-square-o"></i> Improve this doc
    </button>
```

Resulting in this error (when the link is clicked): `Uncaught SyntaxError: Invalid or unexpected token`

**Comment by utsav0209** [comment]
@ZacharyKlein @graemerocher Do you think [here](https://github.com/micronaut-projects/micronaut-guides/blob/f04751c45c28d77cb88abf631d569756408d012b/gradle/guide-build.gradle#L59) it should be `${githubBranch}` and not `$githubBranch`? Could it be the cause of new lines being added after the branch name?

**Comment by graemerocher** [comment]
Looks like it could be yes

**Comment by utsav0209** [comment]
> Looks like it could be yes

@graemerocher could you guide me for the further steps? Should I just put a PR for this or are there any more steps that I should follow?

**Comment by graemerocher** [comment]
Actually no I don't think it is that, must be where the property is defined

**Comment by utsav0209** [comment]
> Actually no I don't think it is that, must be where the property is defined

@graemerocher yeah I thought so too, I tried the CLI command described [here](https://github.com/micronaut-projects/micronaut-build/blob/8885f884ff3ecddcb8dfbc3f258e7a7f3d15a4b2/src/main/groovy/io/micronaut/build/MicronautDocsPlugin.groovy#L203) and it does return a newline character at the end! tho I am not sure if this relates here or not!?
