### ISSUE TITLE
Micronaut 3.0.3 create-app missing dependency

### ISSUE THREAD

**Issue by mike-brown-1** [micronaut-projects/micronaut-docs#47]
Following the Quick Start, mn create-app hello-world fails to add testImplementation 'io.projectreactor:reactor-test:3.4.8' to build.grade.  This causes the test HelloClientSpec to fail to compile.  Suggest adding to documentation to add this dependency, which lets the developer decide if they really want to add it to their project or not.

**Comment by ilopmar** [comment]
Starting with Micronaut 3 we do not expose any reactive library for users by default and it's up to the users to add one if they need it. This is explained here https://docs.micronaut.io/latest/guide/index.html#_project_reactor_used_internally_instead_of_rxjava2

![image](https://user-images.githubusercontent.com/559192/136768839-74d33f55-87ad-40fd-9625-85f7b0d3c2a3.png)

And in the linked docs: https://docs.micronaut.io/latest/guide/index.html#reactiveConfigs

![image](https://user-images.githubusercontent.com/559192/136768934-24cb3080-9b9c-4186-a19b-f0accb91309d.png)

If you think this documentation is not clear enough, please submit a PR where you think it's appropriate using the **"Improve this docs"** button in the docs :-)
